### ISSUE TITLE
maximizing playback window in windows version makes the player forgot the previous player placement and size.

### ISSUE THREAD

**Issue by Jurtaani** [f1multiviewer/issue-tracker#183]
so when you doubleclick on the player to maximize or to restore it, it will forget the previous window placement and size and instead jsut switches between full screen and full sized normal window.
it seem to be triggered when user doubleclicks on the video, because when you just use the maximize/restore button on bottom of the window it works as expected and window will maximize and return back to the original place.

**Comment by Jurtaani** [comment]
i can also confirm that this same thing happens if you use the right click "toggle full screen" button as well.
it also will make the player forget it's original placement.

**Comment by f1multiviewer** [comment]
I think this has since been fixed, correct?
