### ISSUE TITLE
[Linux] Update notifications appear to have stopped since 1.9.0

### ISSUE THREAD

**Issue by csutcliff** [f1multiviewer/issue-tracker#262]
The last time I got an update notification on Linux was to upgrade to 1.9.0, nothing for 1.9.2/1.9.6. Possibly related to the Windows/MacOS auto update?

**Comment by csutcliff** [comment]
Got the update notification for 1.9.7 on 1.9.6. Not sure why it wasn't working on 1.9.0 but I'm closing this now.

**Comment by f1multiviewer** [comment]
Oh interesting, thanks for the update! 💚
