### ISSUE TITLE
Please remove war propaganda

### ISSUE THREAD

**Issue by Dediqated** [f1multiviewer/issue-tracker#299]
Please remove the political statements from this app. Sport should be free from this. F1 itself prohibits these kind of statements so why should you add them?

Or at least make them optional.

**Comment by f1multiviewer** [comment]
F1 has had plenty of "No war" statements and many drivers still show support through various means for Ukraine.

I'm not F1, I'm not affiliated with them, and I'll support peace no matter what. If it bothers you, use https://f1tv.formula.com
