### ISSUE TITLE
Races don't load on Mac

### ISSUE THREAD

**Issue by alexjshepler** [f1multiviewer/issue-tracker#307]
When I try to load the races, the only thing that will load is the Replay Live Timing, but the F1 TV won't load or any of the on board cameras, but when I watch the practices they all load fine.

![image](https://user-images.githubusercontent.com/19987488/201575149-ae8160a0-c881-4306-859f-954400a4e1ef.png)
I'm on Ventura 13.0.1

**Comment by f1multiviewer** [comment]
Hey, this isn't really the place to get help, the Discord server was introduced for that: https://discord.gg/f1mv
