### ISSUE TITLE
Main window too big on a MBP 13" screen, can't resize vertically

### ISSUE THREAD

**Issue by x-f** [f1multiviewer/issue-tracker#327]
I just updated my F1MW version from 1.8.5 to 1.12.4, and now it turns out the main window is too big for my MacbookPro 13" non-retina screen – lower part, including the Settings button, goes behind the Dock.
This window cannot be resized vertically anymore either, it was available with older versions, there was no minimum window size.

![multiviewer-main window too big](https://user-images.githubusercontent.com/481453/220183320-f661affe-a3d0-45fc-a572-bce63c4fcd03.jpg)

(Thanks for the otherwise superb app!)

**Comment by x-f** [comment]
Apparently fixed now in v1.12.8 – main window is resizable again.
Thank you!

**Comment by f1multiviewer** [comment]
Correct, I updated it, forgot to close, thanks!
