### ISSUE TITLE
Unable to download due to invalid certificate

### ISSUE THREAD

**Issue by pvanb** [f1multiviewer/issue-tracker#361]
I get an invalid certificate warning when trying to download the latest version and am subsequently blocked by security policies on my computer. The latter is not your concern, and I'm sure most people can click on "visit this website" and download anyway, but that isn't an option for me.

![Screen Shot 2023-03-17 at 10 47 58 AM](https://user-images.githubusercontent.com/823278/225939175-5d477cf6-ad96-4a0e-bf45-2b02ef33a8e9.png)

**Comment by LapsTimeOFF** [comment]
Hi, can you please join our [Discord](https://muvi.gg/discord) and create a ticket in #help ?
