### ISSUE TITLE
Avoid making it too bloated

### ISSUE THREAD

**Issue by AppleFlapp** [f1multiviewer/issue-tracker#383]
Would be nice if the app doesn't get overloaded with bloat.
As such please skip Nascar and Indy. Both have nothing to do with F1.
I would rather see a dedicated app with low processor load.

**Comment by xlsupport** [comment]
The addional code for the Yankee series should be in separate dlls. Not needed?, not loaded.
Imo the app is pretty efficient, but be aware that LIVE streams are encrypted so require processing. 

But yes, there's differences in what you can do on a machine with more cores and a dedicated graphics card, compared to running it on a laptop.  Certainly when you start adding 4k monitors ;-)

**Comment by f1multiviewer** [comment]
Not relevant
