### ISSUE TITLE
Set Size -> Exact Resolution options set width instead of height

### ISSUE THREAD

**Issue by Unmoon** [f1multiviewer/issue-tracker#404]
Selecting Set Size -> 1080p sets the window size to 1078x609 instead of the expected 1920x1080. 720p sets size to 719x406.

I'd like to use this option to set the window size to exact same as the stream itself is.

![image](https://github.com/f1multiviewer/issue-tracker/assets/7273082/9357d59f-e38d-4d32-a8ba-f3b3837037a1)

Multiviewer version: v1.19.3, using 64bit .deb installer  
OS: Pop!_OS 22.04 LTS

**Comment by f1multiviewer** [comment]
This is fixed now :)
