### ISSUE TITLE
Intel download contains ARM-only binary that cannot be launched on Intel Macs

### ISSUE THREAD

**Issue by core-code** [f1multiviewer/issue-tracker#468]
https://releases.multiviewer.app/download/137423394/MultiViewer.for.F1-1.29.0-x64.dmg

this is a ARM ("Apple Silicon") only binary and cannot be launched on Intel Macs.

something did go wrong here....

**Comment by f1multiviewer** [comment]
You have likely changed the file name in the URL, which isn't sufficient. The file ID earlier in the download link is important, as it uniquely identifies the binary to respond with.

<img width="250" alt="image" src="https://github.com/f1multiviewer/issue-tracker/assets/106821994/e1f74a43-99cf-45fb-981f-c109f438d573">

As you can see, the one you can download from the website contains the correct binary.


```
Intel: https://releases.multiviewer.app/download/137423940/MultiViewer.for.F1-1.29.0-x64.dmg
Arm: https://releases.multiviewer.app/download/137423394/MultiViewer.for.F1-1.29.0-arm64.dmg
```

**Comment by core-code** [comment]
thanks you are correct and sorry for the noise

quite weird though that an invalid download URL actually doesn't fail to download but just downloads something else :-)
