### ISSUE TITLE
2024 Team colours and icons

### ISSUE THREAD

**Issue by KlingonDragon** [f1multiviewer/issue-tracker#476]
Two 2024 teams are incorrectly displaying the Red Bull team icon and are missing from the colour customisation menu:
- Stake F1 Team Kick Sauber
- Visa Cash App RB F1 Team

*v1.31.0*

**Comment by M0UL** [comment]
this will be fixed in the next update

**Comment by KlingonDragon** [comment]
Can you give an estimate for when this update will be available?

**Comment by lukepistrol** [comment]
In the session overview currently VCARB, Aston Martin, as well as HAAS show the wrong team logo (Red Bull):

![Screenshot 2024-02-29 at 12 12 39](https://github.com/f1multiviewer/issue-tracker/assets/9460130/19ba5218-be92-4b50-ab8e-38fb6f615aa6)


In the timing screen only VCARB shows the wrong logo:

![Screenshot 2024-02-29 at 12 17 12](https://github.com/f1multiviewer/issue-tracker/assets/9460130/7f9d811c-364b-42f5-b0e2-1a86c23c8e63)
