### ISSUE TITLE
If you pause a live stream and continue later the progress bar goes out of boungs

### ISSUE THREAD

**Issue by crimsdings** [f1multiviewer/issue-tracker#505]
![mvf1](https://github.com/f1multiviewer/issue-tracker/assets/886421/8c04fdd8-95c7-4dc7-b5b7-9c203f335680)

OS: Windows 10
App version matches latest release version 1.31.7 (beta channel)

Started "Pre-Race Show" - paused for 20 minutes mid stream - continued watching - progress bar and progress dot went out of bounds of the window.

**Comment by f1multiviewer** [comment]
This is an upstream issue at bitmovin, we can't fix this ourselves. We'll update the player when it's fixed.
